Repository JBraunsmaJr/Devry-Service-Bot, pull requests merged in 2021-07, with the labels that each got.

#22 Corrected docker build file
  DevryBot/Dockerfile
Labels: bug

#28 Implemented the welcome feature
  DevryBot/Bot.cs
  DevryBot/ConfigurationExtensions.cs
  DevryBot/Data/Configs/DiscordSettings.json
  DevryBot/Data/Configs/WelcomeSettings.json
  DevryBot/DevryBot.csproj
  DevryBot/DevryBotWorker.cs
  DevryBot/Discord/Extensions/StringExtensions.cs
  DevryBot/Discord/Interactions/LectureInviteInteraction.cs
  DevryBot/Discord/SlashCommands/Invite.cs
  DevryBot/Discord/SlashCommands/LectureInvite.cs
  DevryBot/Services/WelcomeHandler.cs
  DevryBot/docker-compose.yml
Labels: feature request

#31 Fixed the bug / error regarding the lecture invite
  DevryBot/Bot.cs
  DevryBot/Data/Configs/DiscordSettings.json
  DevryBot/Discord/Extensions/RolesDictionaryExtensions.cs
  DevryBot/Discord/Interactions/LectureInviteInteraction.cs
  DevryBot/Discord/SlashCommands/Invite.cs
  DevryBot/Discord/SlashCommands/LectureInvite.cs
  DevryBot/Install.sh
  DevryBot/docker-compose.yml
Labels: Critical, bug

#38 Updated welcome message
  DevryBot/Data/Configs/WelcomeSettings.json
Labels: bug

#39 Snippet assistance - Python support
  DevryBot/ConfigurationExtensions.cs
  DevryBot/Data/Configs/SnippetSettings.json
  DevryBot/Data/Profiles/Python/ProspectorProfile.yml
  DevryBot/Data/Scripts/Python/python-scan.sh
  DevryBot/DevryBot.csproj
  DevryBot/Discord/SlashCommands/Snippets/CodeReview.cs
  DevryBot/Dockerfile
  DevryBot/Program.cs
  DevryBot/Startup.cs
  DevryDomain/Models/LanguageInfo.cs
  DevryInfrastructure/StorageHandler.cs
  DevryServiceBot.sln
  SnippetAssistant/.dockerignore
  SnippetAssistant/CodeReviewService.cs
  SnippetAssistant/Core/IMessage.cs
  SnippetAssistant/Core/IOutput.cs
  SnippetAssistant/Core/ISummary.cs
  SnippetAssistant/Dockerfile
  SnippetAssistant/Helpers/Html.cs
  SnippetAssistant/Program.cs
  SnippetAssistant/Python/PythonMessage.cs
  SnippetAssistant/Python/PythonOutput.cs
  SnippetAssistant/Python/PythonReport.cs
  SnippetAssistant/Python/PythonSummary.cs
  SnippetAssistant/ReportBase.cs
  SnippetAssistant/SnippetAssistant.csproj
  SnippetAssistant/Views/Python/PythonBlock.cshtml
  SnippetAssistant/Views/Python/PythonErrors.cshtml
  SnippetAssistant/Views/Shared/Main.cshtml
  SnippetAssistant/Views/Shared/Summary.cshtml
Labels: enhancement, feature request

#40 Report volume
  DevryApplication/Tasks/Scheduling/SchedulerBackgroundService.cs
  DevryBot/ConfigurationExtensions.cs
  DevryBot/Data/Configs/DiscordSettings.json
  DevryBot/Discord/SlashCommands/Snippets/CodeReview.cs
  DevryBot/docker-compose.yml
  DevryInfrastructure/StorageHandler.cs
  SnippetAssistant/CodeReviewService.cs
Labels: enhancement, feature request

#41 Images
  DevryBot/Data/Configs/DiscordSettings.json
Labels: enhancement
